name: Python application

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-16.04
    python-version: 3.6

    steps:
    - uses: actions/checkout@v2
    - name: Install linters
      run: |
        pip3 install flake8 black isort
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Lint with isort
      run: |
        isort --check-only -rc .
    - name: Lint with black
      run: |
        black --check --diff .

